# config/database.yml

default: &default
  adapter: sqlite3 # This is for your local dev setup (if you use SQLite)
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  adapter: postgresql       # <--- THIS LINE NEEDS TO BE INDENTED 2 SPACES FROM 'production:'
  url: <%= ENV["DATABASE_URL"] %> # <--- THIS LINE NEEDS TO BE INDENTED 2 SPACES FROM 'production:'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000